name: Sync Spreadsheet to CSV

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread oauth2client pandas

      - name: Run sync script
        env:
          GSPREAD_SERVICE_ACCOUNT: ${{ secrets.GSPREAD_SERVICE_ACCOUNT }}
        run: |
          python scripts/sync_spreadsheet_to_csv.py

      - name: Commit and push if CSV changed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add mst_zenn_ideas.csv
          git diff --cached --quiet || (git commit -m "🔄 Auto-sync: update mst_zenn_ideas.csv" && git push)
